version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: al-ci/Dockerfile.dmoj
    container_name: dmoj_app
    image: cbt/dmoj-base
    # ports:
    #   - "8000:8000"  # Exposing port 8000
    volumes:
      - ./site:/app/site  # Volume to persist changes
    environment:
      - DB_HOST=db
      - DB_NAME=dmoj
      - DB_USER=dmoj
      - DB_PASSWORD=nsot98er  # replace with actual password
    depends_on:
      - db
      - redis
    networks:
      - backend
  site:
    container_name: dmoj_site
    build:
      context: .
      dockerfile: ./al-ci/Dockerfile.site
    image: cbt/dmoj-site
    init: true
    restart: unless-stopped
    volumes:
      - assets:/assets/
      - userdatacache:/userdatacache/
      - contestdatacache:/contestdatacache/
      - cache:/cache/
      - ./media/:/media/
      - ./problems/:/problems/
    working_dir: /app/
    networks:
      - backend
    depends_on:
      - web
      - db
      - redis
  celery:
    container_name: dmoj_celery
    build:
      context: .
      dockerfile: ./al-ci/Dockerfile.celery
    image: cbt/dmoj-celery
    init: true
    restart: unless-stopped
    volumes:
      - userdatacache:/userdatacache/
      - contestdatacache:/contestdatacache/
    working_dir: /app/
    networks:
      - backend
    depends_on:
      - web
      - redis
      - db
  bridged:
    container_name: dmoj_bridged
    build:
      context: .
      dockerfile: ./al-ci/Dockerfile.bridge
    image: cbt/dmoj-bridged
    init: true
    restart: unless-stopped
    volumes:
      - ./problems/:/problems/
    working_dir: /app/
    networks:
      - backend
    depends_on:
      - web
      - redis
      - db
    ports:
      - 9998:9998
      - 9999:9999
  # wsevent:
  #   container_name: vnoj_wsevent
  #   build:
  #     context: .
  #     dockerfile: ./wsevent/Dockerfile
  #   image: vnoj/vnoj-wsevent
  #   init: true
  #   restart: unless-stopped
  #   volumes:
  #     - ./repo/:/app/site/
  #   working_dir: /app/site
  #   env_file: [environment/mysql.env, environment/site.env]
  #   networks: [site, nginx]
  #   depends_on: [base]
  #   #ports:
  #   #  - 15100:15100
  #   #  - 15101:15101
  #   #  - 15102:15102
  nginx:
    container_name: dmoj_nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - assets:/assets/
      - userdatacache:/userdatacache/
      - contestdatacache:/contestdatacache/
      - cache:/cache/
      - ./media/:/media/
      - ./config/nginx/:/etc/nginx/conf.d/
    networks:
      - backend
    depends_on:
      - site
  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nsot98er  # Set root password
      MYSQL_DATABASE: dmoj
      MYSQL_USER: dmoj
      MYSQL_PASSWORD: nsot98er  # Replace with actual password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"  # Exposing Redis port
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  assets:
  userdatacache:
  contestdatacache:
  cache:
