# Start with the python:3.10-slim base image
FROM python:3.10-slim

RUN apt install python3-dev python3-pip build-essential libseccomp-dev -y
RUN apt-get install gcc libpq-dev -y
RUN apt-get install python-dev  python-pip -y
RUN apt-get install python3-dev python3-pip python3-venv python3-wheel -y
RUN pip3 install wheel

WORKDIR /app

COPY ./judge-server/ /app/

RUN pip3 install -r environments.txt
RUN dmoj-autoconf