FROM node:alpine

WORKDIR /app
RUN npm install qu ws simplesets commander

COPY site/websocket/ /app/websocket/
COPY config/config.js /app/websocket/config.js

EXPOSE 15100
EXPOSE 15101
EXPOSE 15102

ENTRYPOINT node /app/websocket/daemon.js